### ISSUE TITLE
Allowing queuing for WQ from the quest tracker

### ISSUE THREAD

**Issue by johnsolver** [cheald/WorldQuestAssistant#1]
Not sure why opt for a queue from the map when you can queue from the objective tracker.

A lot of people tend to select several WQs (shift click) before doing their rounds (in the TrackerBlocks). Currently the addon simply doesn't show the buttons for a quest that isn't active (in IsEligibleQuest GetQuestLogIndexByID(questID) ~= 0) removing that condition makes it work as expected ie. allows queuing for any WQ in the tracker.

Is that to avoid abuse, not sure how effective that is given that server-hop exists.

**Comment by saibantes** [comment]
Since 0.6.1-beta: You can queue from the quest tracker and also from the map (with middle mouse button), as advertised by the addon description.
