### ISSUE TITLE
lua error in Kaliels module

### ISSUE THREAD

**Issue by Hemario** [cheald/WorldQuestAssistant#3]
Date: 2017-05-17 18:32:03
ID: 2
Error occured in: Global
Count: 1
Message: ...dOns\WorldQuestAssistant\modules\kaliels_tracker.lua line 16:
   attempt to compare number with nil
Debug:
   ...dOns\WorldQuestAssistant\modules\kaliels_tracker.lua:16:
      ...dOns\WorldQuestAssistant\modules\kaliels_tracker.lua:12
   (tail call): ?
   [C]: SetupTrackerBlocks()
   WorldQuestAssistant\core.lua:73:
      WorldQuestAssistant\core.lua:72
   [C]: ?
   !KalielsTracker\KalielsTracker.lua:490: ObjectiveTracker_Update()
   ...zzard_ObjectiveTracker\Blizzard_ObjectiveTracker.lua:788: ObjectiveTracker_MinimizeButton_OnClick()
   !KalielsTracker\KalielsTracker.lua:1759: ToggleEmptyTracker()
   !KalielsTracker\KalielsTracker.lua:506: ObjectiveTracker_Update()
   !KalielsTracker\KalielsTracker.lua:215:
      !KalielsTracker\KalielsTracker.lua:189
   !KalielsTracker\KalielsTracker.lua:1880:
      !KalielsTracker\KalielsTracker.lua:1879
Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 Enable = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 EnableModule = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 SecureHookScript = <function> defined @Interface\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:410
 defaultModuleLibraries = <table> {
 }
 RawHookScript = <function> defined @Interface\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:395
 GetName = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 name = "WorldQuestAssistant_Kaliel's Tracker Support"
 IsEnabled = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 orderedModules = <table> {
 }
 DisableModule = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
 HookScript = <function> defined @Interface\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:366
 IsHooked = <function> defined @Interface\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:493
 IsModule = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:248
 SetDefaultModuleState = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:418
 SetEnabledState = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:455
 Hook = <function> defined @Interface\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:274
 enabledState = true
 baseName = "WorldQuestAssistant"
 SetupTrackerBlocks = <function> defined @Interface\AddOns\WorldQuestAssistant\modules\kaliels_tracker.lua:12
 OnEnable = <function> defined @Interface\AddOns\WorldQuestAssistant\modules\kaliels_tracker.lua:5
 hooks = <table> {
 }
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:440
 SecureHook = <function> defined @Interface\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:336
 IterateModules = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:468
 UnhookAll = <function> defined @Interface\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:477
 RawHook = <function> defined @Interface\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:313
 Unhook = <function> defined @Interface\AddOns\ElvUI\Libraries\AceHook-3.0\AceHook-3.0.lua:418
 moduleName = "Kaliel's Tracker Support"
 defaultModuleState = true
 Disable = <function> defined @Interface\AddOns\!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:345
}
anchor = !KalielsTrackerFrame {
 0 = <userdata>
 Buttons = !KalielsTrackerButtons {
 }
 Scroll = !KalielsTrackerScroll {
 }
 directionUp = false
 QuestLogButton = !KalielsTrackerQuestLogButton {
 }
 MinimizeButton = !KalielsTrackerMinimizeButton {
 }
 anchorLeft = false
 ActiveButton = !KalielsTrackerActiveButton {
 }
 FilterButton = !KalielsTrackerFilterButton {
 }
 Bar = !KalielsTrackerScrollBar {
 }
 AchievementsButton = !KalielsTrackerAchievementsButton {
 }
}
anchorPoint = "TOPLEFT"
relativePoint = "TOPRIGHT"
(*temporary) = nil
(*temporary) = 960
(*temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
(*temporary) = 1920
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to compare number with nil"
WQA = <table> {
 SetDefaultModuleLibraries = <functi
AddOns:
  KalielsTracker, v2.1.5
  Swatter, v7.4.5714 (TasmanianThylacine)
  AddOnSkins, v3.47
  AdvancedInterfaceOptions, v1.1.4
  AlreadyKnown, v1.13
  AngryKeystones, v
  AngryWorldQuests, v
  APeonsBurden, vv2.5
  Arh, v1.6.4
  ArmoryQuickLink, v3.8
  ArtifactTab, v2.3
  AskMrRobot, v50
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Auctionator, v4.0.17
  AutoBar, v7.2.0.00
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, vv7.2.79
  BadBoyHistory, v
  BadPet, vv1.0.8
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  BonusRollPreview, v70200.39-Release
  BuyEmAll, v3.3.6
  CanIMogIt, v7.2.0.03
  Configator, v5.1.DEV.406(/embedded)
  CQuestCounter, v1.3
  DBMCore, v7.2.6
  DBMDefaultSkin, v
  DBMLegendaryDummy, v2.0
  DBMLootReminder, v1.3
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  DevTools, v1.0
  EasyDelete, v
  ElvUI, v10.52
  ElvUIDataConfig, v1.04
  ElvUIEverySecondCounts, v1.18
  ElvUITankHealth, v1.12
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  FishingBuddy, v1.7.13a
  FixGroups, v1.4.1
  FixOrderHallMap, vv1.0.3
  FontOfPowerStrataFix, v7.2.0.1
  GoGoMount, v7.1.1
  GTFO, v4.42.13
  GuildKicker, v1.1
  HandyNotes, vv1.4.13
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLegionRaresTreasures, v1.01b
  HandyNotesWitheredArmyTraining, v1
  HealthWarning, v1.16
  HiddenArtifactTracker, v
  Informant, v7.4.5714 (TasmanianThylacine)
  ItemLinkLevel, v1.6
  KethoInstanceTimer, vv2.7.2
  KuiMedia, v
  KuiNameplates, v
  KuiNameplatesCore, v
  KuiNameplatesCoreConfig, v
  KuiSpellListConfig, v
  LegionInvasionTimer, vv7.2.10
  LFGMute, v7.1.5.1
  LFGStatusIcon, v5.4.001
  LibExtraTip, v5.12.DEV.423(/embedded)
  m4xLegendary, vv1.0
  MacroToolkit, vv7.2.0.1
  MacroToolkitIcons, v7.2.0.0
  MikScrollingBattleText, v5.7.147
  MSADropDownMenu10, v1.0.1
  MyPersonalNote, v7.0.3.1
  MythicPlusGroupCreation, v0.1
  NomiCakes, v7.2.0.2
  NOP, v07.28 10.05.2017
  NoThunderTotemMap, v1.0
  Oilvl, v6.5.4
  oRA3, vv7.2.2
  Outfitter, v5.19
  Ovale, v@project-version@
  Overachiever, v0.99.7
  ParagonReputation, v1.12
  Pawn, v2.2.5
  Postal, vv3.5.8
  PremadeGroupsFilter, v1.10
  QuickJoinNotifications, v1.13
  QuietMacros, v7.2.0
  Rarity, v1.0
  RarityOptions, v
  RCLootCouncil, v2.3.2
  ReagentBanker, v0.1
  RepSwitch, v7.0.3.8
  SatchelAutoJoin, v7.1.0.1
  SavedInstances, v7.0.8
  SharedMacros, v7.1.5.6
  SimpleObjectiveProgress, vr18
  Skada, v1.6.7
  SlideBar, v7.4.5714 (TasmanianThylacine)
  StealthAlerter, v0.99.25
  Stubby, v7.4.5714 (TasmanianThylacine)
  SubSpec, v2.1.5.0
  SuperGuildInvite, v7.6.0
  Telemancy, v1.1.8
  TellMeWhen, v8.3.3
  TipHelper, v5.12.DEV.405(/embedded)
  Titan, v5.11.3.70200
  TitanBag, v5.11.3.70200
  TitanClock, v5.11.3.70200
  TitanGold, v5.11.3.70200
  TitanLocation, v5.11.3.70200
  TitanLootType, v5.11.3.70200
  TitanPerformance, v5.11.3.70200
  TitanRepair, v5.11.3.70200
  TitanVolume, v5.11.3.70200
  TitanXP, v5.11.3.70200
  TomTom, vv70200-1.0.0
  TrainAll, v
  Vendomatic, v
  WhoWhisperedMe, v40000.1
  WitheredArmyTraining, v1.00
  WorldQuestAssistant, v0.4.2
  BlizRuntimeLib_enUS v7.2.0.70200 <none>
  (ck=1155)

**Comment by cheald** [comment]
Thanks, I'll get it fixed up.

**Comment by saibantes** [comment]
another fix was needed, done now
