### ISSUE TITLE
7.2.5 Broken

### ISSUE THREAD

**Issue by Gorthezar** [cheald/WorldQuestAssistant#4]
Patch 7.2.5 broke this addon.

**Comment by cheald** [comment]
Can you elaborate on what's broken?

**Comment by Gorthezar** [comment]
Can't join groups have to use the finder tool to get into a group.

**Comment by cheald** [comment]
I've pushed 0.6 which should fix this.

**Comment by PekaFat** [comment]
`Message: Interface\FrameXML\LFGList.lua:1733: attempt to index local 'searchText' (a number value)
Time: 06/15/17 08:06:19
Count: 1
Stack: Interface\FrameXML\LFGList.lua:1733: attempt to index local 'searchText' (a number value)Interface\SharedXML\SharedBasicControls.lua:204: in function <Interface\SharedXML\SharedBasicControls.lua:203>
[C]: ?
Interface\FrameXML\LFGList.lua:1733: in function `LFGListSearchPanel_ParseSearchTerms'
Interface\AddOns\WorldQuestAssistant\core.lua:415: in function `FindQuestGroups'
Interface\AddOns\WorldQuestAssistant\core.lua:551: in function `Automate'
[string "WQA_AUTOMATE"]:1: in function <[string "WQA_AUTOMATE"]:1>
Locals: errorMessage = "Interface\FrameXML\LFGList.lua:1733: attempt to index local 'searchText' (a number value)"
DisplayMessageInternal = <function> defined @Interface\SharedXML\SharedBasicControls.lua:187
MESSAGE_TYPE_ERROR = 0`

Got this error when pressing binded button for search groups.
